package org.cj.dao.auto;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.cj.entity.auto.Tercher;
import org.cj.entity.auto.TercherExample;

public interface TercherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    long countByExample(TercherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    int deleteByExample(TercherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    int insert(Tercher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    int insertSelective(Tercher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    List<Tercher> selectByExample(TercherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    Tercher selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") Tercher record, @Param("example") TercherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    int updateByExample(@Param("record") Tercher record, @Param("example") TercherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    int updateByPrimaryKeySelective(Tercher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    int updateByPrimaryKey(Tercher record);
}