package org.cj.entity.auto;

public class Tercher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.id
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.xm
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    private String xm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.xb
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    private String xb;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.id
     *
     * @return the value of teacher.id
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.id
     *
     * @param id the value for teacher.id
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.xm
     *
     * @return the value of teacher.xm
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.xm
     *
     * @param xm the value for teacher.xm
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.xb
     *
     * @return the value of teacher.xb
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.xb
     *
     * @param xb the value for teacher.xb
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }
}