package org.cj.entity.auto;

public class Test {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.id
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.name
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.ext1
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    private String ext1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.ext2
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    private String ext2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.id
     *
     * @return the value of test.id
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.id
     *
     * @param id the value for test.id
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.name
     *
     * @return the value of test.name
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.name
     *
     * @param name the value for test.name
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.ext1
     *
     * @return the value of test.ext1
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.ext1
     *
     * @param ext1 the value for test.ext1
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.ext2
     *
     * @return the value of test.ext2
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.ext2
     *
     * @param ext2 the value for test.ext2
     *
     * @mbg.generated Sun Mar 12 20:57:59 CST 2017
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }
}